-- Run once in the Supabase SQL editor before applying Django migrations.
-- FlatHunter AI uses GeoDjango PointField columns and spatial queries.
create extension if not exists postgis;

create schema if not exists flathunter;

grant usage, create on schema flathunter to postgres;

create table if not exists flathunter.django_migrations (
    id bigint generated by default as identity primary key,
    app varchar(255) not null,
    name varchar(255) not null,
    applied timestamp with time zone not null
);
