# Generated by Django 6.0.7 on 2026-07-16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListingSource",
            fields=[
                ("code", models.SlugField(max_length=48, primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(db_index=True, default=False)),
                ("access_mode", models.CharField(choices=[("demo", "Synthetic demo"), ("api", "Official API"), ("feed", "Official feed"), ("manual", "Manual import")], max_length=16)),
                ("legal_status", models.CharField(default="approved_demo", max_length=32)),
                ("terms_checked_at", models.DateTimeField(blank=True, null=True)),
                ("rate_limit", models.PositiveIntegerField(default=60)),
                ("request_interval", models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ("supports_search", models.BooleanField(default=True)),
                ("supports_details", models.BooleanField(default=True)),
                ("supports_contacts", models.BooleanField(default=False)),
                ("supports_images", models.BooleanField(default=True)),
                ("requires_authentication", models.BooleanField(default=False)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("health_status", models.CharField(default="unknown", max_length=24)),
            ],
            options={"ordering": ("display_name",)},
        ),
        migrations.CreateModel(
            name="RawListing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=128)),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(db_index=True, max_length=64)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("normalized_at", models.DateTimeField(blank=True, null=True)),
                ("normalization_error", models.TextField(blank=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="raw_listings", to="listings.listingsource")),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=128)),
                ("source_url", models.URLField(max_length=500)),
                ("canonical_url", models.URLField(max_length=500)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("deal_type", models.CharField(default="rent", max_length=16)),
                ("property_type", models.CharField(default="apartment", max_length=32)),
                ("country", models.CharField(default="UA", max_length=2)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(db_index=True, max_length=120)),
                ("district", models.CharField(blank=True, db_index=True, max_length=120)),
                ("street", models.CharField(blank=True, max_length=160)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("location_accuracy", models.CharField(default="district", max_length=24)),
                ("price", models.PositiveIntegerField(db_index=True)),
                ("currency", models.CharField(default="UAH", max_length=3)),
                ("price_uah", models.PositiveIntegerField(db_index=True)),
                ("rooms", models.PositiveSmallIntegerField(db_index=True)),
                ("total_area", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floors_total", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("building_type", models.CharField(blank=True, max_length=48)),
                ("renovation_level", models.CharField(blank=True, max_length=48)),
                ("heating_type", models.CharField(blank=True, max_length=48)),
                ("pets_allowed", models.BooleanField(blank=True, null=True)),
                ("children_allowed", models.BooleanField(blank=True, null=True)),
                ("commission_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("is_owner", models.BooleanField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("normalization_version", models.PositiveSmallIntegerField(default=1)),
                ("raw_listing", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="listing", to="listings.rawlisting")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="listings", to="listings.listingsource")),
            ],
            options={"ordering": ("-published_at", "-first_seen_at")},
        ),
        migrations.AddConstraint(model_name="rawlisting", constraint=models.UniqueConstraint(fields=("source", "external_id", "payload_hash"), name="raw_listing_payload_unique")),
        migrations.AddIndex(model_name="rawlisting", index=models.Index(fields=["source", "external_id"], name="raw_source_external_idx")),
        migrations.AddConstraint(model_name="listing", constraint=models.UniqueConstraint(fields=("source", "external_id"), name="listing_source_external_unique")),
        migrations.AddIndex(model_name="listing", index=models.Index(fields=["is_active", "city", "-published_at"], name="listing_active_city_pub_idx")),
        migrations.AddIndex(model_name="listing", index=models.Index(fields=["city", "rooms", "price_uah"], name="listing_city_rooms_price_idx")),
    ]
