# Generated by Django 6.0 for FlatHunter AI Stage 5

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserListingState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_favorite", models.BooleanField(db_index=True, default=False)),
                ("is_hidden", models.BooleanField(db_index=True, default=False)),
                ("is_compared", models.BooleanField(db_index=True, default=False)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_states", to="listings.listing")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listing_states", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="userlistingstate",
            constraint=models.UniqueConstraint(fields=("user", "listing"), name="listing_state_user_unique"),
        ),
        migrations.AddIndex(
            model_name="userlistingstate",
            index=models.Index(fields=["user", "is_favorite"], name="listing_state_favorite_idx"),
        ),
        migrations.AddIndex(
            model_name="userlistingstate",
            index=models.Index(fields=["user", "is_compared"], name="listing_state_compare_idx"),
        ),
    ]
