# Generated by Django 6.0.7 on 2026-07-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("price_uah", models.PositiveIntegerField()),
                ("currency", models.CharField(default="UAH", max_length=3)),
                ("title_hash", models.CharField(max_length=64)),
                ("description_hash", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("street", models.CharField(blank=True, max_length=160)),
                ("rooms", models.PositiveSmallIntegerField()),
                ("total_area", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floors_total", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("building_type", models.CharField(blank=True, max_length=48)),
                ("renovation_level", models.CharField(blank=True, max_length=48)),
                ("heating_type", models.CharField(blank=True, max_length=48)),
                ("pets_allowed", models.BooleanField(blank=True, null=True)),
                ("children_allowed", models.BooleanField(blank=True, null=True)),
                ("commission_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("is_owner", models.BooleanField(blank=True, null=True)),
                ("attributes_summary", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("source_last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analysis_snapshots", to="listings.listing")),
            ],
            options={"ordering": ("-captured_at", "-id")},
        ),
        migrations.CreateModel(
            name="ListingMarketAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("ready", "Ready"), ("insufficient_data", "Insufficient data"), ("stale", "Stale"), ("failed", "Failed"), ("disabled", "Disabled")], db_index=True, default="insufficient_data", max_length=24)),
                ("provider", models.CharField(default="local", max_length=64)),
                ("algorithm_version", models.CharField(default="market-v1", max_length=32)),
                ("input_hash", models.CharField(max_length=64)),
                ("median_price_uah", models.PositiveIntegerField(blank=True, null=True)),
                ("q1_price_uah", models.PositiveIntegerField(blank=True, null=True)),
                ("q3_price_uah", models.PositiveIntegerField(blank=True, null=True)),
                ("median_price_per_sqm", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("target_price_per_sqm", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("deviation_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("comparable_count", models.PositiveIntegerField(default=0)),
                ("confidence_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("confidence_label", models.CharField(choices=[("none", "None"), ("low", "Low"), ("medium", "Medium"), ("high", "High")], default="none", max_length=16)),
                ("comparable_ids", models.JSONField(blank=True, default=list)),
                ("selection_summary", models.JSONField(blank=True, default=dict)),
                ("explanation", models.TextField(blank=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("valid_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="market_assessments", to="listings.listing")),
            ],
            options={"ordering": ("-calculated_at", "-id")},
        ),
        migrations.CreateModel(
            name="ListingPriceHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("previous_price_uah", models.PositiveIntegerField()),
                ("new_price_uah", models.PositiveIntegerField()),
                ("change_amount_uah", models.IntegerField()),
                ("change_percent", models.DecimalField(decimal_places=2, max_digits=8)),
                ("direction", models.CharField(choices=[("increase", "Increase"), ("decrease", "Decrease")], max_length=16)),
                ("changed_at", models.DateTimeField()),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="price_history", to="listings.listing")),
                ("snapshot", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="price_event", to="analysis.listingsnapshot")),
            ],
            options={"ordering": ("-changed_at", "-detected_at")},
        ),
        migrations.CreateModel(
            name="ListingRiskAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("ready", "Ready"), ("insufficient_data", "Insufficient data"), ("stale", "Stale"), ("failed", "Failed"), ("disabled", "Disabled")], db_index=True, default="insufficient_data", max_length=24)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("level", models.CharField(choices=[("low", "Low risk"), ("review", "Review"), ("elevated", "Elevated risk"), ("insufficient_data", "Insufficient data")], default="insufficient_data", max_length=24)),
                ("signals", models.JSONField(blank=True, default=list)),
                ("protective_signals", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("safety_advice", models.TextField(blank=True)),
                ("algorithm_version", models.CharField(default="risk-v1", max_length=32)),
                ("input_hash", models.CharField(max_length=64)),
                ("calculated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("valid_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="risk_assessments", to="listings.listing")),
                ("market_assessment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="risk_assessments", to="analysis.listingmarketassessment")),
            ],
            options={"ordering": ("-calculated_at", "-id")},
        ),
        migrations.AddConstraint(
            model_name="listingsnapshot",
            constraint=models.UniqueConstraint(fields=("listing", "content_hash"), name="analysis_snapshot_listing_hash_unique"),
        ),
        migrations.AddIndex(
            model_name="listingsnapshot",
            index=models.Index(fields=["listing", "-captured_at"], name="analysis_snapshot_latest_idx"),
        ),
        migrations.AddConstraint(
            model_name="listingmarketassessment",
            constraint=models.UniqueConstraint(fields=("listing", "input_hash"), name="analysis_market_listing_input_unique"),
        ),
        migrations.AddConstraint(
            model_name="listingmarketassessment",
            constraint=models.CheckConstraint(condition=models.Q(("confidence_score__gte", 0), ("confidence_score__lte", 100)), name="analysis_market_confidence_range"),
        ),
        migrations.AddIndex(
            model_name="listingmarketassessment",
            index=models.Index(fields=["listing", "-calculated_at"], name="analysis_market_latest_idx"),
        ),
        migrations.AddConstraint(
            model_name="listingpricehistory",
            constraint=models.CheckConstraint(condition=models.Q(("change_amount_uah", 0), _negated=True), name="analysis_price_change_nonzero"),
        ),
        migrations.AddIndex(
            model_name="listingpricehistory",
            index=models.Index(fields=["listing", "-changed_at"], name="analysis_price_history_idx"),
        ),
        migrations.AddConstraint(
            model_name="listingriskassessment",
            constraint=models.UniqueConstraint(fields=("listing", "input_hash"), name="analysis_risk_listing_input_unique"),
        ),
        migrations.AddConstraint(
            model_name="listingriskassessment",
            constraint=models.CheckConstraint(condition=models.Q(("score__gte", 0), ("score__lte", 100)), name="analysis_risk_score_range"),
        ),
        migrations.AddIndex(
            model_name="listingriskassessment",
            index=models.Index(fields=["listing", "-calculated_at"], name="analysis_risk_latest_idx"),
        ),
    ]
