# Generated by Django 6.0.7 on 2026-07-16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="SearchProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(db_index=True, max_length=120)),
                ("deal_type", models.CharField(choices=[("rent", "Оренда"), ("buy", "Купівля")], default="rent", max_length=16)),
                ("price_min", models.PositiveIntegerField(blank=True, null=True)),
                ("price_max", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="UAH", max_length=3)),
                ("rooms", models.JSONField(blank=True, default=list)),
                ("desired_districts", models.JSONField(blank=True, default=list)),
                ("excluded_districts", models.JSONField(blank=True, default=list)),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("occupants", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ("children", models.BooleanField(default=False)),
                ("pets", models.JSONField(blank=True, default=dict)),
                ("property_types", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="search_profiles", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="ImportantPlace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("max_distance_km", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("max_walk_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_drive_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_transit_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("importance", models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("search_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="important_places", to="searches.searchprofile")),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("frequency", models.CharField(choices=[("instant", "Миттєво"), ("15m", "Кожні 15 хвилин"), ("hourly", "Щогодини"), ("twice_daily", "Двічі на день"), ("daily", "Щодня")], default="instant", max_length=24)),
                ("min_match_score", models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("max_risk_score", models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("daily_limit", models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ("quiet_hours_enabled", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(default="23:00")),
                ("quiet_hours_end", models.TimeField(default="08:00")),
                ("notify_price_changes", models.BooleanField(default=True)),
                ("notify_reactivated", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="notification_preference", to="searches.searchprofile")),
            ],
        ),
        migrations.AddConstraint(
            model_name="searchprofile",
            constraint=models.CheckConstraint(condition=models.Q(("price_min__isnull", True), ("price_max__isnull", True), ("price_min__lte", models.F("price_max")), _connector="OR"), name="search_price_range_valid"),
        ),
        migrations.AddIndex(model_name="searchprofile", index=models.Index(fields=["user", "is_active"], name="searches_se_user_id_bda538_idx")),
    ]
